<?php $viewModel = $block->getData('feedback_form_view_model'); ?>

<form class="form contact"
      action="<?= $block->escapeUrl($viewModel->getActionUrl()) ?>"
      id="feedback-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend">
            <span><?= $block->escapeHtml(__('Leave your feedback')) ?></span>
        </legend><br />

        <div class="field choice newsletter">
            <input type="checkbox"
                   name="is_anonymous"
                   title="<?= $escaper->escapeHtmlAttr(__('Is Anonymous Feedback')) ?>"
                   value="1"
                   id="reply_notification"                       
                   class="checkbox">
            <label for="is_anonymous" class="label">
                <span><?= $escaper->escapeHtml(__('Is Anonymous Feedback')) ?></span>
            </label>
        </div> 
        
        
        <div class="field name required">
            <label class="label" for="author_name">
                <span><?= $block->escapeHtml(__('Name')) ?></span>
            </label>
            <div class="control">
                <input name="author_name" id="author_name"
                       title="<?= $block->escapeHtmlAttr(__('Name')) ?>" value="<?= $viewModel->getCustomerName() ?>"
                       class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>  

        <div class="field email required">
            <label class="label" for="author_email">
                <span><?= $block->escapeHtml(__('Email')) ?></span>
            </label>
            <div class="control">
                <input name="author_email" id="author_email"
                       title="<?= $block->escapeHtmlAttr(__('FeedbackEmail')) ?>" value="<?= $viewModel->getCustomerEmail() ?>"
                       class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>

        <div class="field comment required">
            <label class="label" for="message">
                <span><?= $block->escapeHtml(__('Leave your feedback here')) ?></span>
            </label>
            <div class="control">
                <textarea name="message" id="message"
                          title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>"
                          class="input-text" cols="5" rows="3" data-validate="{required:true}">
                </textarea>
            </div>
        </div>
        
        <div class="field choice newsletter">
            <input type="checkbox"
                   name="reply_notification"
                   title="<?= $escaper->escapeHtmlAttr(__('Notify me about reply')) ?>"
                   value="1"
                   id="reply_notification"                       
                   class="checkbox">
            <label for="reply_notification" class="label">
                <span><?= $escaper->escapeHtml(__('Notify me about reply')) ?></span>
            </label>
        </div>    

    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">            
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>"
                    class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>
