<?php $viewModel = $block->getData('feedback_history_view_model'); ?>
<div>                        
    <?= $block->getChildBlock('feedback_sorter')->toHtml() ?>
</div>
<!-- Display feedback info -->
<div class="feedback-list" style="margin-top: 60px;">
    <?php if ($viewModel->getAllCustomerFeedbacksNumber()): ?>

        <!-- Display feedback info -->
        <div class="feedback-list">
            <?php foreach ($block->getCollection() as $feedback): ?>
                <div class="feedback-item" style="background-color: aliceblue; margin: 5px; padding: 20px;">
                    <p>
                        <?= $block->escapeHtml($feedback->getAuthorName()) ?> |
                        <?= $viewModel->getFeedbackDate($feedback) ?> |
                        <?= $viewModel->getFeedbackStatus($feedback) ?> 
                    </p>
                    <div class="ratings-column">                        
                        <?= $block->getChildBlock('list_ratings')->setFeedback($feedback)->toHtml() ?>
                    </div>
                    <p><?= $block->escapeHtml($feedback->getMessage()) ?></p>
                </div>

                <!-- Display feedback replies if any -->
                <?php foreach ($viewModel->getRepliesByFeedbackId($feedback->getId()) as $reply): ?>
                    <?php if ($reply->getReplyText()): ?>
                        <div class="feedback-item" style="background-color: oldlace; margin: 20px; padding: 20px;">
                            <div>
                                <p>
                                    <?= $block->escapeHtml($viewModel->getReplyAuthorName($reply)) ?> |
                                    <?= $reply->getReplyCreationTime() ?>
                                </p>
                                <p>
                                    <?= $block->escapeHtml($reply->getReplyText()) ?>
                                </p>
                            </div>
                        </div>
                    <?php endif ?>
                <?php endforeach; ?>
                <br>
            <?php endforeach; ?>
        </div>

    <?php else: ?>
        <div class="message info empty"><span><?= $escaper->escapeHtml(__('You have submitted no feedbacks.')) ?></span></div>
    <?php endif; ?>

    <!-- Display pagination --> 
    <?php if ($block->getChildHtml('pager')): ?>
        <div class="order-products-toolbar toolbar bottom">
            <?= $block->getChildHtml('pager'); ?>
        </div>
    <?php endif ?> 
</div>