<?php
/** @var \Magento\Framework\View\Element\Template $block */
$form = $block->getForm();
?>
<?php if ($form): ?>
    <form action="<?= $form->getAction(); ?>" method="<?= $form->getMethod(); ?>" enctype="<?= $form->getEnctype(); ?>" id="<?= $form->getId(); ?>">
        <?= $form->getElement('base_fieldset')->toHtml(); ?>
        <div class="actions">
            <button type="submit" class="action-save primary">
                <span><?= __('Save') ?></span>
            </button>
        </div>
    </form>
<?php endif; ?>
