<div>
    <div class="feedback-statistic">
        <p><?= __('Total number of submitted feedbacks: %1', $block->getAllFeedbackNumber()) ?></p>
        <p><?= __('Total number of active feedbacks: %1', $block->getActiveFeedbackNumber()) ?></p>
    </div>
    <div class="toolbar">
        <?= $block->getPaginationHtml() ?>
    </div>
    <div class="feedback-list">
        <?php foreach ($block->getCollection() as $feedback): ?>
            <div class="feedback-item" style="background-color: aliceblue; margin: 5px;">
                <p>
                    <?= $block->escapeHtml($feedback->getAuthorName()) ?> |
                    <?= $block->getFeedbackDate($feedback) ?>
                </p>
                <p><?= $block->escapeHtml($feedback->getMessage()) ?></p>
            </div>
        <?php endforeach; ?>
    </div>
    <div class="toolbar">
        <?= $block->getPaginationHtml() ?>
    </div>
    <div class="action">
        <button id="add" title="<?= __('Add Feedback') ?>"
                type="button" class="action scalable primary"
                onclick="location.href = '<?= $block->escapeUrl($block->getAddFeedbackUrl()) ?>';">
            <span><?= __('Add Feedbaack') ?></span>
        </button>
    </div>
</div
